---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: typesense-common-bootstrap-key
type: Opaque
data:
  typesense-api-key: SXdpVG9CcnFYTHZYeTJNMG1TS1hPaGt0dlFUY3VWUloxc1M5REtsRUNtMFFwQU93R1hoanVIVWJLQnE2ejdlSQ==
---
apiVersion: v1
data:
  TYPESENSE_HEALTHY_READ_LAG: "1000"
  TYPESENSE_HEALTHY_WRITE_LAG: "500"
kind: ConfigMap
metadata:
  name: c-otc-1-server-configuration
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-otc-1
spec:
  image: typesense/typesense:28.0
  replicas: 5
  resources:
    limits:
      cpu: "2000m"
      memory: "2048Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  storage:
    size: 10Gi
    storageClassName: csi-disk
#  ingress:
#    host: ts.example.de
#    ingressClassName: nginx
#    clusterIssuer: opentelekomcloud-letsencrypt
  adminApiKey:
    name: typesense-common-bootstrap-key
#  scrapers:
#    - name: docusaurus-example-com
#      image: typesense/docsearch-scraper:0.11.0
#      config: "{\"index_name\":\"docusaurus-example\",\"start_urls\":[\"https://docusaurus.example.com/\"],\"sitemap_urls\":[\"https://docusaurus.example.com/sitemap.xml\"],\"sitemap_alternate_links\":true,\"stop_urls\":[\"/tests\"],\"selectors\":{\"lvl0\":{\"selector\":\"(//ul[contains(@class,'menu__list')]//a[contains(@class, 'menu__link menu__link--sublist menu__link--active')]/text() | //nav[contains(@class, 'navbar')]//a[contains(@class, 'navbar__link--active')]/text())[last()]\",\"type\":\"xpath\",\"global\":true,\"default_value\":\"Documentation\"},\"lvl1\":\"header h1\",\"lvl2\":\"article h2\",\"lvl3\":\"article h3\",\"lvl4\":\"article h4\",\"lvl5\":\"article h5, article td:first-child\",\"lvl6\":\"article h6\",\"text\":\"article p, article li, article td:last-child\"},\"strip_chars\":\" .,;:#\",\"custom_settings\":{\"separatorsToIndex\":\"_\",\"attributesForFaceting\":[\"language\",\"version\",\"type\",\"docusaurus_tag\"],\"attributesToRetrieve\":[\"hierarchy\",\"content\",\"anchor\",\"url\",\"url_without_anchor\",\"type\"]},\"conversation_id\":[\"833762294\"],\"nb_hits\":46250}"
#      schedule: '*/2 * * * *'
  additionalServerConfiguration:
    name: c-otc-1-server-configuration
  metrics:
    release: promstack
---
#apiVersion: ts.opentelekomcloud.com/v1alpha1
#kind: TypesenseCluster
#metadata:
#  labels:
#    app.kubernetes.io/name: typesense-operator
#    app.kubernetes.io/managed-by: kustomize
#  name: c-otc-2
#spec:
#  image: typesense/typesense:26.0
#  replicas: 1
#  storage:
#    storageClassName: csi-disk
#---
#apiVersion: ts.opentelekomcloud.com/v1alpha1
#kind: TypesenseCluster
#metadata:
#  labels:
#    app.kubernetes.io/name: typesense-operator
#    app.kubernetes.io/managed-by: kustomize
#  name: c-otc-3
#spec:
#  image: typesense/typesense:26.0
#  replicas: 3
#  storage:
#    storageClassName: csi-obs